In [ ]:
!unzip EMOPIA_1.0.zip

Archive:  EMOPIA_1.0.zip
   creating: EMOPIA_1.0/
   creating: EMOPIA_1.0/tagging_lists/
  inflating: __MACOSX/EMOPIA_1.0/._tagging_lists  
  inflating: EMOPIA_1.0/.DS_Store    
  inflating: __MACOSX/EMOPIA_1.0/._.DS_Store  
  inflating: EMOPIA_1.0/metadata_by_song.csv  
   creating: EMOPIA_1.0/songs_lists/
  inflating: __MACOSX/EMOPIA_1.0/._songs_lists  
   creating: EMOPIA_1.0/midis/
  inflating: EMOPIA_1.0/README.md    
  inflating: __MACOSX/EMOPIA_1.0/._README.md  
  inflating: EMOPIA_1.0/label.csv    
  inflating: __MACOSX/EMOPIA_1.0/._label.csv  
   creating: EMOPIA_1.0/scripts/
   creating: EMOPIA_1.0/metadata/
  inflating: __MACOSX/EMOPIA_1.0/._metadata  
  inflating: EMOPIA_1.0/tagging_lists/Q1_K6OFDxBU370.txt  
  inflating: __MACOSX/EMOPIA_1.0/tagging_lists/._Q1_K6OFDxBU370.txt  
  inflating: EMOPIA_1.0/tagging_lists/Q1_zmZHNy9T8Pg.txt  
  inflating: __MACOSX/EMOPIA_1.0/tagging_lists/._Q1_zmZHNy9T8Pg.txt  
  inflating: EMOPIA_1.0/tagging_lists/Q3_PLfFWFZflQU.txt  
  inflating

In [ ]:
import os

# List the contents of the unzipped folder
os.listdir('EMOPIA_1.0')  # Adjust the folder name if necessary

['.DS_Store',
 'label.csv',
 'scripts',
 'metadata_by_song.csv',
 'tagging_lists',
 'README.md',
 'songs_lists',
 'metadata',
 'midis']

In [ ]:
!pip install muspy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 46.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.1/119.1 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 3.9 MB/s eta 0:00:00
  Created wheel for pretty-midi: filename=pretty_midi-0.2.10-py3-none-any.whl size=5592287 sha256=027a9c892d31bc113bc77a090d7069703c654ae166b2c5c4b709d432874645fc
  Stored in directory: /root/.cache/pip/wheels/cd/a5/30/7b8b7f58709f5150f67f98fde4b891ebf0be9ef07a8af49f25
Successfully built pretty-midi
  Attempting uninstall: packaging
    Found existing installation: packaging 24.1
    Uninstalling packaging-24.1:
      Successfully uninstalled packaging-24.1


In [ ]:
# List the contents of the current directory
!ls

EMOPIA_1.0  EMOPIA_1.0.zip  __MACOSX  sample_data


In [ ]:
import pandas as pd

# Load the label.csv file
labels_df = pd.read_csv("/content/EMOPIA_1.0/label.csv")

# Display the first few rows
print(labels_df.head())

# Load the metadata_by_song.csv file
metadata_df = pd.read_csv("/content/EMOPIA_1.0/metadata_by_song.csv")

# Display the metadata
print(metadata_df.head())

                 ID  4Q annotator
0  Q1_0vLPYiPN7qY_0   1         D
1  Q1_0vLPYiPN7qY_1   1         D
2  Q1_0vLPYiPN7qY_2   1         D
3  Q1_1Qc15G0ZHIg_1   1         D
4  Q1_1Qc15G0ZHIg_2   1         D
        songID  num_Q1  num_Q2  num_Q3  num_Q4  DominantQ
0  e8NQ2NH0nc8       2       0       0       0          1
1  HQ8ISDX6PiI       0       0       0       2          4
2  ZTrEoB8T9YA       0       3       0       0          2
3  3N2G21U7guk       3       0       0       4          4
4  _8v0MFBZoco       2       0       0       0          1


In [ ]:
import pretty_midi

def load_midi(filename):
    # Load the MIDI file
    midi_data = pretty_midi.PrettyMIDI(filename)
    return midi_data

# Example: Process one of the MIDI files listed in the dataset
midi_file = '/content/EMOPIA_1.0/midis/Q1_0vLPYiPN7qY_0.mid'
midi_data = load_midi(midi_file)

In [ ]:
print(labels_df.columns)

Index(['ID', '4Q', 'annotator'], dtype='object')


In [ ]:
# Extract the emotion labels from the '4Q' column
emotion_labels = labels_df['4Q']

# Check the first few values of the emotion labels
print(emotion_labels.head())

0    1
1    1
2    1
3    1
4    1
Name: 4Q, dtype: int64


In [ ]:
# Mapping 4Q to descriptive emotions
emotion_mapping = {
    'Q1': 'Happy/Excited',
    'Q2': 'Angry/Tense',
    'Q3': 'Sad/Depressed',
    'Q4': 'Calm/Relaxed'
}

# Apply the mapping to the emotion labels
emotion_labels_mapped = emotion_labels.map(emotion_mapping)

# Check the mapped emotion labels
print(emotion_labels_mapped.head())

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: 4Q, dtype: object


In [ ]:
!pip install muspy
!pip install pretty_midi

In [ ]:
import pandas as pd

# Load the CSV file
labels_df = pd.read_csv("/content/EMOPIA_1.0/label.csv")

# Extract the emotion labels from the '4Q' column
emotion_labels = labels_df['4Q']

# Display the unique values to check for unexpected entries
print("Unique values in '4Q':", emotion_labels.unique())

# Mapping numeric 4Q values to descriptive emotions
emotion_mapping = {
    1: 'Happy/Excited',   # Q1
    2: 'Angry/Tense',     # Q2
    3: 'Sad/Depressed',   # Q3
    4: 'Calm/Relaxed'     # Q4
}

# Apply the mapping to the emotion labels and handle NaN values
emotion_labels_mapped = emotion_labels.map(emotion_mapping)

# If there are any NaN values, print a warning and fill them
if emotion_labels_mapped.isnull().any():
    print("Warning: Some emotion labels could not be mapped. Filling NaN values with 'Unknown'.")
    emotion_labels_mapped.fillna('Unknown', inplace=True)

# Check the mapped emotion labels
print(emotion_labels_mapped.head())

Unique values in '4Q': [1 2 3 4]
0    Happy/Excited
1    Happy/Excited
2    Happy/Excited
3    Happy/Excited
4    Happy/Excited
Name: 4Q, dtype: object


In [ ]:
import pretty_midi
import numpy as np

# Function to load and process MIDI files
def midi_to_sequences(filename, seq_length=50):
    midi_data = pretty_midi.PrettyMIDI(filename)
    sequences = []
    for instrument in midi_data.instruments:
        for note in instrument.notes:
            sequences.append([note.start, note.end, note.pitch, note.velocity])
    return np.array(sequences[:seq_length])

# Example of loading one MIDI file (update the path accordingly)
midi_sequences = midi_to_sequences('/content/EMOPIA_1.0/midis/Q1_0vLPYiPN7qY_0.mid')

# Example: Show the first few sequences
print(midi_sequences[:5])

[[ 0.20703125  0.44921875 91.         86.        ]
 [ 0.40755208  0.52994792 86.         73.        ]
 [ 0.21354167  0.609375   79.         76.        ]
 [ 0.21354167  0.80989583 58.         58.        ]
 [ 0.82421875  1.02994792 67.         54.        ]]


In [ ]:
'''import tensorflow as tf

# Create the LSTM-based model for music generation
def create_music_model(input_shape, condition_shape):
    # Input for note sequences
    inputs = tf.keras.Input(shape=input_shape)
    # Input for emotion condition (one-hot encoded)
    conditions = tf.keras.Input(shape=condition_shape)

    # LSTM layers for sequence generation
    x = tf.keras.layers.LSTM(128, return_sequences=True)(inputs)
    x = tf.keras.layers.LSTM(128)(x)

    # Concatenate the emotion conditions
    combined = tf.keras.layers.Concatenate()([x, conditions])

    # Output dense layers for generating notes (e.g., pitch, duration)
    pitch_output = tf.keras.layers.Dense(128, activation='softmax')(combined)  # Example: pitch output
    duration_output = tf.keras.layers.Dense(1)(combined)  # Example: duration output

    return tf.keras.Model([inputs, conditions], [pitch_output, duration_output])

# Define input shapes (adjust based on your data)
input_shape = (50, 4)  # e.g., 50 time steps with 4 features (start, end, pitch, velocity)
condition_shape = (4,)  # Assuming 4 emotion classes

# Create the model
model = create_music_model(input_shape, condition_shape)
model.summary()'''

"import tensorflow as tf\n\n# Create the LSTM-based model for music generation\ndef create_music_model(input_shape, condition_shape):\n    # Input for note sequences\n    inputs = tf.keras.Input(shape=input_shape)\n    # Input for emotion condition (one-hot encoded)\n    conditions = tf.keras.Input(shape=condition_shape)\n\n    # LSTM layers for sequence generation\n    x = tf.keras.layers.LSTM(128, return_sequences=True)(inputs)\n    x = tf.keras.layers.LSTM(128)(x)\n\n    # Concatenate the emotion conditions\n    combined = tf.keras.layers.Concatenate()([x, conditions])\n\n    # Output dense layers for generating notes (e.g., pitch, duration)\n    pitch_output = tf.keras.layers.Dense(128, activation='softmax')(combined)  # Example: pitch output\n    duration_output = tf.keras.layers.Dense(1)(combined)  # Example: duration output\n\n    return tf.keras.Model([inputs, conditions], [pitch_output, duration_output])\n\n# Define input shapes (adjust based on your data)\ninput_shape = (50, 

In [ ]:
import tensorflow as tf
import numpy as np

# Create the LSTM-based model for music generation
def create_music_model(input_shape, condition_shape):
    # Input for note sequences
    inputs = tf.keras.Input(shape=input_shape)

    # Input for emotion condition (one-hot encoded)
    conditions = tf.keras.Input(shape=condition_shape)

    # LSTM layers for sequence generation
    x = tf.keras.layers.LSTM(128, return_sequences=True)(inputs)

    # Repeat the emotion condition across time steps (50 steps)
    repeated_conditions = tf.keras.layers.RepeatVector(input_shape[0])(conditions)

    # Concatenate the LSTM output with the repeated emotion conditions
    combined = tf.keras.layers.Concatenate()([x, repeated_conditions])

    # Output dense layers for generating notes (e.g., pitch, duration)
    pitch_output = tf.keras.layers.TimeDistributed(
        tf.keras.layers.Dense(128, activation='softmax')
    )(combined)  # Now predicting 50 timesteps, each with 128 possible pitch classes

    duration_output = tf.keras.layers.TimeDistributed(
        tf.keras.layers.Dense(1)
    )(combined)  # Now predicting 50 timesteps, each with one duration value

    return tf.keras.Model([inputs, conditions], [pitch_output, duration_output])

# Define input shapes (adjust based on your data)
input_shape = (50, 4)  # e.g., 50 time steps with 4 features (start, end, pitch, velocity)
condition_shape = (4,)  # Assuming 4 emotion classes

# Create the model
model = create_music_model(input_shape, condition_shape)
model.summary()

# Prepare the data (replace this with actual data preparation logic)
X_sequences = np.random.rand(1, 50, 4)  # Input MIDI sequences
y_pitch = np.random.randint(0, 128, size=(1, 50))  # Random pitch for demonstration
y_duration = np.random.rand(1, 50, 1)  # Random durations for demonstration
emotion_inputs = np.array([[0, 0, 0, 1]])  # Example one-hot encoded emotion (Q1)

# One-hot encode the target pitch values to match the model's output
y_pitch_one_hot = tf.keras.utils.to_categorical(y_pitch, num_classes=128)

# Compile the model
model.compile(optimizer='adam', loss=['categorical_crossentropy', 'mean_squared_error'])

# Train the model (this is just a simple example; use actual data)
model.fit([X_sequences, emotion_inputs], [y_pitch_one_hot, y_duration], epochs=30)

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 50, 4)          │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ input_layer_1             │ (None, 4)              │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ lstm (LSTM)               │ (None, 50, 128)        │         68,096 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ repeat_vector             │ (None, 50, 4)          │              0 │ input_layer_1[0][0]    │
│ (RepeatVector)            │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ concatenate (Concatenate) │ (None, 50, 132)        │              0 │ lstm[0][0],            │
│                           │                        │                │ repeat_vector[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ time_distributed          │ (None, 50, 128)        │         17,024 │ concatenate[0][0]      │
│ (TimeDistributed)         │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ time_distributed_1        │ (None, 50, 1)          │            133 │ concatenate[0][0]      │
│ (TimeDistributed)         │                        │                │                        │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 85,253 (333.02 KB)

 Trainable params: 85,253 (333.02 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 8s 8s/step - loss: 5.2158
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 5.0970
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 5.0084
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 4.9497
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 4.9244
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 4.9262
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 4.9213
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 4.9006
Epoch 9/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 4.8755
Epoch 10/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 4.8532
Epoch 11/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 4.8353
Epoch 12/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 4.8202
Epoch 13/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 4.8058
Epoch 14/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 4.7902
Epoch 15/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 4.7718
Epoch 16/30
1/1 ━━━━━━━━━━━━━━━━━

In [ ]:
def generate_music(model, seed_sequence, emotion_input, num_notes=250):
    generated_notes = seed_sequence.copy()  # Start with the seed sequence
    for _ in range(num_notes):
        # Predict the next note
        next_note = model.predict([generated_notes, emotion_input])

        # Extract the pitch predictions and duration predictions
        next_pitch = next_note[0]  # Pitch output
        next_duration = next_note[1]  # Duration output

        # Get the last pitch from next_pitch, which is shaped (1, 128)
        next_pitch = np.argmax(next_pitch[:, -1, :], axis=1)  # Get the index of the highest probability
        next_duration = next_duration[:, -1, :]  # Get the last duration prediction

        # Create a new note based on the last pitch and duration
        new_note = np.array([[0.0, 0.0, next_pitch[0], next_duration[0][0]]])  # [start, end, pitch, velocity]

        # Append the predicted note to the sequence
        generated_notes = np.append(generated_notes[:, 1:, :], new_note.reshape(1, 1, -1), axis=1)  # Shift sequence left and add new note

    return generated_notes

In [ ]:
# Example: Use a random seed and user-defined emotion input (Q1: Happy)
seed_sequence = np.random.rand(1, 50, 4)  # Example seed sequence
emotion_input = np.array([[0, 0, 0, 1]])  # Example emotion input (Q1: Happy)

# Generate music
generated_music = generate_music(model, seed_sequence, emotion_input)

# Check the shape of the generated music
print("Shape of generated music:", generated_music.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━

In [ ]:
!pip install pretty_midi

In [ ]:
import pretty_midi

def notes_to_midi(generated_notes, output_file):
    midi = pretty_midi.PrettyMIDI()
    instrument = pretty_midi.Instrument(program=0)  # Acoustic Grand Piano

    for note in generated_notes[0]:  # Adjust based on your output structure
        start, end, pitch, velocity = note
        midi_note = pretty_midi.Note(
            velocity=int(velocity),
            pitch=int(pitch),
            start=float(start),
            end=float(end)
        )
        instrument.notes.append(midi_note)

    midi.instruments.append(instrument)
    midi.write(output_file)

In [ ]:
# Assuming generated_music contains the generated notes
notes_to_midi(generated_music, 'generated_music.mid')

In [ ]:
# Step 1: Install PrettyMIDI if not done already
!pip install pretty_midi
!apt-get install fluidsynth # Make sure fluidsynth is installed

# Step 2: Define the notes_to_midi function
import pretty_midi

def notes_to_midi(generated_notes, output_file):
    midi = pretty_midi.PrettyMIDI()
    instrument = pretty_midi.Instrument(program=0)  # Acoustic Grand Piano

    # Check if generated_notes is not empty and contains notes
    if generated_notes.size > 0 and generated_notes[0].size > 0: # Check the size of the arrays instead of their truthiness.
        for note in generated_notes[0]:  # Assuming generated_notes is structured as (1, num_notes, features)
            start, end, pitch, velocity = note
            midi_note = pretty_midi.Note(
                velocity=int(velocity),
                pitch=int(pitch),
                start=float(start),
                end=float(end)
            )
            instrument.notes.append(midi_note)

    midi.instruments.append(instrument)
    midi.write(output_file)

# Step 3: Generate MIDI file from generated music
notes_to_midi(generated_music, 'generated_music.mid')

# Step 4: Play the generated MIDI file
from IPython.display import Audio

# Load the generated MIDI file
midi_data = pretty_midi.PrettyMIDI('generated_music.mid')

# Synthesize audio
audio_data = midi_data.fluidsynth()

# Check if audio_data is empty
if audio_data.size == 0:
    print("Error: No audio generated from MIDI. Check MIDI generation or Fluidsynth installation.")
else:
    # Check the shape of the audio data
    print(audio_data.shape)  # Inspect the shape of audio_data

    # Ensure that audio_data is a 1D array
    if audio_data.ndim > 1:
        audio_data = audio_data.flatten()  # Flatten if it's not 1D

    # Play the audio
    Audio(audio_data, rate=44100)

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  fluid-soundfont-gm libevdev2 libfluidsynth3 libgudev-1.0-0 libinput-bin libinput10
  libinstpatch-1.0-2 libmd4c0 libmtdev1 libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5
  libqt5svg5 libqt5widgets5 libwacom-bin libwacom-common libwacom9 libxcb-icccm4 libxcb-image0
  libxcb-keysyms1 libxcb-render-util0 libxcb-util1 libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1
  libxkbcommon-x11-0 qsynth qt5-gtk-platformtheme qttranslations5-l10n timgm6mb-soundfont
Suggested packages:
  fluid-soundfont-gs qt5-image-formats-plugins qtwayland5 jackd
The following NEW packages will be installed:
  fluid-soundfont-gm fluidsynth libevdev2 libfluidsynth3 libgudev-1.0-0 libinput-bin libinput10
  libinstpatch-1.0-2 libmd4c0 libmtdev1 libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5
  libqt5svg5 libqt5widgets5 libwacom-bin libwacom-common libwacom9 libxcb-icc

In [ ]:
import pretty_midi

midi_data = pretty_midi.PrettyMIDI('generated_music.mid')

# Check the number of instruments and notes in the MIDI file
for instrument in midi_data.instruments:
    print(f'Instrument {instrument.program} has {len(instrument.notes)} notes.')

In [ ]:
# Check the shape and content of generated_music
print("Generated Music Shape:", generated_music.shape)
print("Generated Music Sample:", generated_music)

Generated Music Shape: (1, 50, 4)
Generated Music Sample: [[[ 0.          0.         23.          0.67536306]
  [ 0.          0.         23.          0.55476314]
  [ 0.          0.         37.          0.55560589]
  [ 0.          0.         23.          0.67536306]
  [ 0.          0.         23.          0.55476308]
  [ 0.          0.         37.          0.55560589]
  [ 0.          0.         23.          0.67536294]
  [ 0.          0.         23.          0.5547632 ]
  [ 0.          0.         37.          0.55560589]
  [ 0.          0.         23.          0.67536306]
  [ 0.          0.         23.          0.5547632 ]
  [ 0.          0.         37.          0.55560589]
  [ 0.          0.         23.          0.67536306]
  [ 0.          0.         23.          0.5547632 ]
  [ 0.          0.         37.          0.55560589]
  [ 0.          0.         23.          0.67536306]
  [ 0.          0.         23.          0.55476308]
  [ 0.          0.         37.          0.55560589]
  [ 0.

In [ ]:
def notes_to_midi(generated_notes, output_file):
    midi = pretty_midi.PrettyMIDI()
    instrument = pretty_midi.Instrument(program=0)  # Acoustic Grand Piano

    for note in generated_notes[0]:  # Assuming the format is (1, num_notes, features)
        start, end, pitch, velocity = note


        # Validate notes before adding
        if pitch < 0 or pitch > 127:
            continue  # Skip invalid pitches
        if start < 0 or end < start:  # Ensure valid start and end times
            continue

        midi_note = pretty_midi.Note(
            velocity=int(velocity),
            pitch=int(pitch),
            start=float(start),
            end=float(end)
        )
        instrument.notes.append(midi_note)

    # Only write the MIDI file if there are notes
    if len(instrument.notes) > 0:
        midi.instruments.append(instrument)
        midi.write(output_file)
    else:
        print("No valid notes to write to MIDI file.")

In [ ]:
# Check for valid pitches and timing
for note in generated_music[0]:  # Assuming generated_music is structured as (1, num_notes, features)
    start, end, pitch, velocity = note
    print(f'Start: {start}, End: {end}, Pitch: {pitch}, Velocity: {velocity}')

Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753630638122559
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.55476313829422
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753630638122559
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.5547630786895752
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753629446029663
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.5547631978988647
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753630638122559
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.5547631978988647
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753630638122559
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.5547631978988647
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocit

In [ ]:
import pretty_midi

def notes_to_midi(generated_notes, output_file):
    midi = pretty_midi.PrettyMIDI()
    instrument = pretty_midi.Instrument(program=0)  # Acoustic Grand Piano

    current_time = 0.0  # Initialize current time for sequential note generation

    for note in generated_notes[0]:  # Assuming the format is (1, num_notes, features)
        start, end, pitch, velocity = note

        # If the model-generated start and end times are invalid, fix them
        if start == 0.0 and end == 0.0:
            start = current_time
            end = start + 0.5  # Give a fixed duration of 0.5 seconds
            current_time += 0.5  # Increment time for the next note

        # Scale the velocity to be in the range of 0-127 for MIDI
        velocity = max(0, min(127, int(velocity * 127)))

        # Ensure pitch is within valid range (0-127)
        pitch = max(0, min(127, int(pitch)))

        # Only add the note if the pitch is valid
        if pitch >= 0 and pitch <= 127:
            midi_note = pretty_midi.Note(
                velocity=int(velocity),
                pitch=int(pitch),
                start=float(start),
                end=float(end)
            )
            instrument.notes.append(midi_note)

    # Only write the MIDI file if there are valid notes
    if len(instrument.notes) > 0:
        midi.instruments.append(instrument)
        midi.write(output_file)
        print(f"MIDI file saved as {output_file}.")
    else:
        print("No valid notes to write to the MIDI file.")

# Example of saving the generated music to a MIDI file
notes_to_midi(generated_music, 'generated_music_fixed.mid')

# Example of checking the generated notes for valid pitch and velocity
for note in generated_music[0]:
    start, end, pitch, velocity = note
    print(f"Start: {start}, End: {end}, Pitch: {pitch}, Velocity: {velocity}")

MIDI file saved as generated_music_fixed.mid.
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753630638122559
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.55476313829422
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753630638122559
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.5547630786895752
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753629446029663
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.5547631978988647
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753630638122559
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.5547631978988647
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666992
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.6753630638122559
Start: 0.0, End: 0.0, Pitch: 23.0, Velocity: 0.5547631978988647
Start: 0.0, End: 0.0, Pitch: 37.0, Velocity: 0.5556058883666

In [ ]:
num_notes_to_generate = 200
generated_music = generate_music(model, seed_sequence, emotion_input)
notes_to_midi(generated_music, 'generated_music.mid')

# Load and check the MIDI file
midi_data = pretty_midi.PrettyMIDI('generated_music.mid')
for instrument in midi_data.instruments:
    print(f'Instrument {instrument.program} has {len(instrument.notes)} notes.')


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━

In [ ]:
!pip install music21

In [ ]:
from music21 import converter

# Load the generated MIDI file
midi_data = converter.parse('generated_music.mid')

# Play the MIDI file
midi_data.show('midi')  # This will play the MIDI file

In [ ]:
print(emotion_input)

[[0 0 0 1]]
